#!/usr/bin/bash
  rm *.deb
  bundle update
  [ -f apache-archiva-1.3.5-bin.tar.gz ] || wget http://www.mirrorservice.org/sites/ftp.apache.org//archiva/binaries/apache-archiva-1.3.5-bin.tar.gz
  bundle exec fpm -n archiva -v 1.3.5 --architecture all -s tar -t deb --prefix /usr/share apache-archiva-1.3.5-bin.tar.gz

